#ifndef CONSTANTS_H
#define CONSTANTS_H

#define DISPLAY_I2C_ADDRESS 0x3F
#define REED_SWITCH_DELAY 50
#define TOUCH_BUTTON_DELAY 100

#define DAY 86400000L

#define ON LOW
#define OFF HIGH

#define TEMPERATURE_HYSTERESIS 0.3F 
#define HUMIDITY_HYSTERESIS 5

#define UPDATE_PERIOD 2000
#define ROTATION_PERIOD 2000

#define WET_PERIOD 120000L
#define WET_TIME 300

#define MENU_SWITCH_PERIOD 300000L

#define MIN_TEMPERATURE 36
#define MAX_TEMPERATURE 38
#define DELTA_TEMPERATURE 0.1

#define MIN_HUMIDITY 0
#define MAX_HUMIDITY 100
#define DELTA_HUMIDITY 1

#define MIN_ROT_PER_DAY 0
#define MAX_ROT_PER_DAY 24
#define DELTA_ROT_PER_DAY 1

#define ALARM_TEMPERATURE 39
#define STOP_TEMPERATURE 43

#define MAX_ARGS 4
#define MAX_CMD_LENGTH 255
#define MAX_ARG_LENGTH 63

#define NO_PERIOD 0xFFFFFFFFUL

#endif
